-- RupayAid Initial Migration
-- This file is generated by Prisma + manual trigger additions.
-- For production, run: npx prisma migrate dev --name init
-- Then manually apply the trigger migrations.

-- ============================================================================
-- TRIGGER: Block UPDATE/DELETE on payment_transactions (immutable)
-- ============================================================================

CREATE OR REPLACE FUNCTION deny_payment_transaction_modifications()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'payment_transactions is immutable: UPDATE and DELETE operations are not permitted';
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_deny_payment_transaction_update
  BEFORE UPDATE ON payment_transactions
  FOR EACH ROW EXECUTE FUNCTION deny_payment_transaction_modifications();

CREATE TRIGGER trg_deny_payment_transaction_delete
  BEFORE DELETE ON payment_transactions
  FOR EACH ROW EXECUTE FUNCTION deny_payment_transaction_modifications();

-- ============================================================================
-- TRIGGER: Block UPDATE/DELETE on ledger_entries (immutable append-only)
-- ============================================================================

CREATE OR REPLACE FUNCTION deny_ledger_entry_modifications()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'ledger_entries is immutable: UPDATE and DELETE operations are not permitted';
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_deny_ledger_entry_update
  BEFORE UPDATE ON ledger_entries
  FOR EACH ROW EXECUTE FUNCTION deny_ledger_entry_modifications();

CREATE TRIGGER trg_deny_ledger_entry_delete
  BEFORE DELETE ON ledger_entries
  FOR EACH ROW EXECUTE FUNCTION deny_ledger_entry_modifications();

-- ============================================================================
-- TRIGGER: Block UPDATE/DELETE on ledgers.current_balance
--          (only allow INSERT via ledger_entries)
-- ============================================================================

CREATE OR REPLACE FUNCTION deny_ledger_balance_direct_update()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.current_balance IS DISTINCT FROM NEW.current_balance THEN
    RAISE EXCEPTION 'ledger.current_balance cannot be modified directly: use ledger_entries';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_deny_ledger_balance_update
  BEFORE UPDATE ON ledgers
  FOR EACH ROW EXECUTE FUNCTION deny_ledger_balance_direct_update();

-- ============================================================================
-- TRIGGER: Block UPDATE/DELETE on loan_application_state_events (immutable)
-- ============================================================================

CREATE OR REPLACE FUNCTION deny_state_event_modifications()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'loan_application_state_events is immutable: cannot update or delete';
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_deny_state_event_update
  BEFORE UPDATE ON loan_application_state_events
  FOR EACH ROW EXECUTE FUNCTION deny_state_event_modifications();

CREATE TRIGGER trg_deny_state_event_delete
  BEFORE DELETE ON loan_application_state_events
  FOR EACH ROW EXECUTE FUNCTION deny_state_event_modifications();

-- ============================================================================
-- TRIGGER: Block UPDATE/DELETE on audit_logs (immutable)
-- ============================================================================

CREATE OR REPLACE FUNCTION deny_audit_log_modifications()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'audit_logs is immutable: UPDATE and DELETE operations are not permitted';
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_deny_audit_log_update
  BEFORE UPDATE ON audit_logs
  FOR EACH ROW EXECUTE FUNCTION deny_audit_log_modifications();

CREATE TRIGGER trg_deny_audit_log_delete
  BEFORE DELETE ON audit_logs
  FOR EACH ROW EXECUTE FUNCTION deny_audit_log_modifications();

-- ============================================================================
-- FUNCTION: Verify ledger entry hash chain on INSERT
-- ============================================================================

CREATE OR REPLACE FUNCTION verify_ledger_entry_hash_chain()
RETURNS TRIGGER AS $$
DECLARE
  last_hash TEXT;
BEGIN
  -- Find the most recent entry for this ledger
  SELECT entry_hash INTO last_hash
  FROM ledger_entries
  WHERE ledger_id = NEW.ledger_id
  ORDER BY txn_seq DESC
  LIMIT 1;

  -- If there is a prior entry, NEW.prevEntryHash must match it
  IF last_hash IS NOT NULL AND (NEW.prev_entry_hash IS NULL OR NEW.prev_entry_hash != last_hash) THEN
    RAISE EXCEPTION 'Ledger entry hash chain broken: expected prev_entry_hash %, got %', last_hash, NEW.prev_entry_hash;
  END IF;

  -- For the very first entry, prevEntryHash should be NULL
  IF last_hash IS NULL AND NEW.prev_entry_hash IS NOT NULL THEN
    RAISE EXCEPTION 'First ledger entry must have NULL prev_entry_hash';
  END IF;

  -- Verify txnSeq is strictly greater than last entry
  IF last_hash IS NOT NULL THEN
    IF NEW.txn_seq <= (SELECT txn_seq FROM ledger_entries WHERE ledger_id = NEW.ledger_id ORDER BY txn_seq DESC LIMIT 1) THEN
      RAISE EXCEPTION 'txn_seq must be strictly monotonically increasing';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_verify_ledger_hash_chain
  BEFORE INSERT ON ledger_entries
  FOR EACH ROW EXECUTE FUNCTION verify_ledger_entry_hash_chain();

-- ============================================================================
-- INDEXES: Additional performance indexes beyond Prisma-managed ones
-- ============================================================================

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loan_applications_created
  ON loan_applications (created_at DESC);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_payments_gateway_ref
  ON payments (gateway_ref);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_payments_tx_ref
  ON payments (tx_ref);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_repayment_schedules_due_status
  ON repayment_schedules (due_date, status)
  WHERE status IN ('SCHEDULED', 'PAST_DUE', 'DEFAULTED');

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_notifications_pending
  ON notifications (status, created_at)
  WHERE status IN ('QUEUED', 'PENDING');

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_logs_created_actor
  ON audit_logs (created_at DESC, changed_by_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sessions_expiry_active
  ON sessions (expires_at, status)
  WHERE status = 'ACTIVE';
