-- Admin KYC / auth audit action types.
ALTER TYPE "AuditLogActionType" ADD VALUE IF NOT EXISTS 'KYC_VIEWED';
ALTER TYPE "AuditLogActionType" ADD VALUE IF NOT EXISTS 'KYC_DECLINED';
ALTER TYPE "AuditLogActionType" ADD VALUE IF NOT EXISTS 'ADMIN_LOGIN';
ALTER TYPE "AuditLogActionType" ADD VALUE IF NOT EXISTS 'ADMIN_LOGOUT';
